apiVersion: v1
kind: ConfigMap
metadata:
  name: qm-configurations
data:
  qminit.mqsc: |
    DEFINE QLOCAL('MVP.DEAD.LETTER.QUEUE') REPLACE
    ALTER QMGR DEADQ('MVP.DEAD.LETTER.QUEUE')
    ALTER QMGR CONNAUTH('') CHLAUTH(DISABLED)
    REFRESH SECURITY(*) TYPE(CONNAUTH)
    DEFINE CHANNEL('MVP.APP.SVRCONN') CHLTYPE(SVRCONN) MCAUSER('mqm') REPLACE
    DEFINE QLOCAL('MVP.COP.REQ') REPLACE
    DEFINE QLOCAL('MVP.COP.RES') REPLACE
    DEFINE QLOCAL('TXT.LOCAL') REPLACE
